### ISSUE TITLE
How to setup with mongoose/graphql

### ISSUE THREAD

**Issue by hennessyevan** [kaviarjs/nova#16]
I'm trying to compare using this in my mongoose/graphql app. I have a few questions about the setup though.

1.  Where do I use addLinks? The schema declaration? The graphql resolver function?
2.  Can I piggyback off of the mongoose schema for addLinks?

In a simple way, I have something that looks like. How would I go about converting this to use nova?

```js
// Models
const postSchema = new mongoose.Schema({
  title: String,
  author: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'user',
  },
})

const Post = mongoose.model('post', postSchema)

const userSchema = new mongoose.Schema({
  firstName: String,
  lastName: String,
})

const User = mongoose.model('user', userSchema)

// Resolver
const Query = {
  posts: async () => {
    return await Post.find().populate('author')
  },
}
```

**Comment by theodorDiaconu** [comment]
Step 1:

Read this: https://github.com/kaviarjs/nova/blob/master/docs/index.md#linking-collections

Step 2:
Create the links by using `addLinks(Post.collection, { user: { field: 'author', collection: User.collection } });`

Step 3:
Query it using `query(Post.collection, { user: { firstName: 1 } })`
