### ISSUE TITLE
Explain intersection

### ISSUE THREAD

**Issue by kratam** [kaviarjs/nova#21]
Can you please explain and/or add examples of `intersection`?

This is the relevant part in nova:
```
        // Intersection is what they have in common
        // This is the best way to secure your graph. By stating explicitly what you allow query-ing
        intersect: {},
```

The [boilerplate](https://github.com/kaviarjs/boilerplate) doesn't have this option.

What should it look like? Can it be a function to return something based on the current user/user's roles?

**Comment by theodorDiaconu** [comment]
@kratam intersection is a body, for example if we're querying users:

```js
{
  firstName: 1,
  lastName: 1,
  games: { 
    name: 1,
  },
}
```

This will prevent graphql for querying other links. Make sense, it INTERSECTS your specified graph with what graphql requests, and gives back only what it allows.

**Comment by kratam** [comment]
Thanks, it makes sense. Can I allow/deny fields based on the user? I'm thinking about a function instead of an object, e.g.:
```
intersect: context => ({ firstName: 1, lastName: context.user.isAdmin ? 1 : 0 })
```

**Comment by theodorDiaconu** [comment]
You can specify a different intersection based on the user indeed. Why do you need it inside intersect as a function?

**Comment by kratam** [comment]
I'm not sure if I need it. I'm just trying to figure out how to upgrade from grapher with nova.

In grapher I had several firewall functions that modified `params.restrictions` (based on the logged in user, the current date, etc), then consumed these restrictions in `embody` to change the query. And `intersect` seems to be the closest to `embody`.

(sorry for the late answer)
