### ISSUE TITLE
(feature request) 

### ISSUE THREAD

**Issue by Fen747** [kaviarjs/nova#24]
**Is your feature request related to a problem? Please describe.**
Currently, the package offers a "not so useful" typescript support. It could, and probably should imho, use type parameters instead of `any` to make a real difference, by allowing autocompletion based on interfaces representing the mongo document.

**Describe the solution you'd like**
For exemple, with Grapher in Meteor, I've extended mongo types to allow Grapher to read the collection documents interface, and provide error prevention and autocompletion when creating queries and links (for example, an inversed link will look for the remote collection interface to make sure the new `field` has first correctly been declared in its interface as a Mongo.GrapherLink<T>, one of my custom types)

**Describe alternatives you've considered**
Staying on Grapher at the moment, but I'd be glad to contribute and move to Nova ASAP

**Additional context**
N/A

**Comment by theodorDiaconu** [comment]
Sounds interesting. I agree, we should have that.
